### signup
Post http://localhost:3000/auth/signup HTTP//1.1
Content-Type: application/json

{
  "email":"anwar1@gmail.com",
  "password":"1234"
}

### get all users
GET http://localhost:3000/auth/users HTTP//1.1

### get a user
GET http://localhost:3000/auth/4 HTTP//1.1

### update user
PATCH http://localhost:3000/auth/4 HTTP//1.1
Content-Type: application/json

{
  "email":"anwarTarek@gmail.com",
  "password":"anwar"

}
